server:
  port: 9090
  context-path: /

spring:

  #Dubbo 1.0.1集成
  dubbo:
    appname: dubbo-service
    registry: zookeeper://192.168.137.1:2181
    protocol: dubbo
    port: 20880

#Dubbo 2.1.0集成
#  dubbo:
#    application:
#      name: dubbo-service
#    registry:
#      address: zookeeper://192.168.137.1:2181
#    protocol:
#      name: dubbo
#      port: 20880
      
#数据源配置      
  datasource:
    name: w1
    url: jdbc:mysql://127.0.0.1:3306/w1?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    
#Mybatis实体类配置    
mybatis:
  mapper-locations: classpath:mapper/*.xml